language: python

python:
  - 3.7

env:
  global:
    DEV_BRANCH=dev
    RELEASE_BRANCH=main
    TEST_VECTORS_ROOT=$HOME/nemtech/test-vectors

cache: pip

addons:
  apt:
    packages:
    - zbar-tools

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: lint
      script:
        - isort --check-only --line-length 140 symbolchain/core/* symbolchain/tests/* symbolchain/vectors
        - pycodestyle --config=.pycodestyle -- symbolchain/core/* symbolchain/tests/* symbolchain/vectors
        - pylint --load-plugins pylint_quotes -- symbolchain/core/* symbolchain/tests/* symbolchain/vectors

    - stage: test
      name: "Unit tests"
      script:
        - python3 -m unittest discover -v symbolchain.tests

    - name: "Test vectors"
      if: branch = env(DEV_BRANCH) OR branch = env(RELEASE_BRANCH)
      script:
        - git clone --depth=1 --branch=main https://github.com/nemtech/test-vectors.git $TEST_VECTORS_ROOT
        - python3 -m symbolchain.vectors.all --blockchain nis1 --vectors "$TEST_VECTORS_ROOT/nis1"
        - python3 -m symbolchain.vectors.all --blockchain symbol --vectors "$TEST_VECTORS_ROOT"

    - stage: alpha package
      name: "Alpha / dev package"
      if: branch = env(DEV_BRANCH)
      script: echo "deployment"
      deploy:
        on:
          branch: $DEV_BRANCH
        provider: pypi
        username: $PYPI_USER
        password: $PYPI_PASS
        distributions: 'sdist bdist_wheel'
